### ISSUE TITLE
logpoints were out of order

### ISSUE THREAD

**Issue by jasonLaster** [WebReplay/webreplay-devtools#103]
I can't reproduce this in webreplay or firefox nightly, but it happens everytime in chrome and brave so i'm guessing it's a css thing

<img width="793" alt="Screen Shot 2020-06-09 at 5 20 30 PM" src="https://user-images.githubusercontent.com/254562/84213505-b2730780-aa75-11ea-93c3-608d3b88ff0e.png">

**Comment by jasonLaster** [comment]
it should be a, b, c

**Comment by bhackett1024** [comment]
I think this is because maybeSortVisibleMessages returns a boolean instead of a number, and the messages end up getting sorted differently.
