### ISSUE TITLE
Replaying google fails

### ISSUE THREAD

**Issue by jasonLaster** [WebReplay/webreplay-devtools#143]
This is a nice example, but it is what i see as my web replay new tab

- https://webreplay.io/view?id=cc0d0ef6-d2e2-47f9-9a10-efd7d9fbe335
- https://webreplay.io/view?id=49991ec4-834b-48cf-ae56-b9dfa48011e4

<img width="1208" alt="Screen Shot 2020-06-18 at 10 19 38 AM" src="https://user-images.githubusercontent.com/254562/85052180-567f4180-b14d-11ea-8d87-8c6edce7fe4e.png">

**Comment by jasonLaster** [comment]
https://webreplay.io/view?id=324406a8-7e7e-4601-9e2b-f59ef92846b3

<img width="1342" alt="Screen Shot 2020-06-18 at 1 40 07 PM" src="https://user-images.githubusercontent.com/254562/85069616-47a68800-b169-11ea-9154-f9d7b955c3bc.png">

**Comment by jasonLaster** [comment]
still seeing some issues here
https://webreplay.io/view?id=4c60fd27-0954-40da-bb4b-b58e3770be0a

basically, it doesnt seem to replay

**Comment by bhackett1024** [comment]
I think the issues affecting google.com are the same ones that were affecting jam.dev (crashes when trying to replay a recording made with an existing FF profile).  If you still see crashes, feel free to reopen (or refile) with STR.
