### ISSUE TITLE
Record https://www.gatsbyjs.org/

### ISSUE THREAD

**Issue by jasonLaster** [WebReplay/webreplay-devtools#153]
it slows down when you try to scroll, likely due to some css animations and scrolling behavior.

should be a good test case

**Comment by bhackett1024** [comment]
When testing this I found that I couldn't scroll at all, and the page stopped responding to inputs.  I fixed that (the main thread event loop in the middleman process could starve if a lot of repainting was happening) and scrolling is much smoother now.  I also fixed a recording mismatch that was happening sometimes, and the page should work pretty well now.

**Comment by bhackett1024** [comment]
Actually this still crashes when replaying, I'll look again on monday.

**Comment by bhackett1024** [comment]
This WFM now /shrug
