### ISSUE TITLE
replaying https://gmnz5.csb.app/ fails

### ISSUE THREAD

**Issue by jasonLaster** [WebReplay/webreplay-devtools#154]
https://gmnz5.csb.app/ is a processing p5 app that has a pretty fast draw loop

going to the the site with firefox nightly shows the index.ts file and lets you set a log point, with web replay it seems to record, but doesn't show any files.

My hunch is this is a replay crash

https://webreplay.io/view?id=a6cb2cd9-e539-40f2-aa3b-63f3a187b3df

**Comment by jasonLaster** [comment]
@bhackett1024 what's the status here?

**Comment by bhackett1024** [comment]
This had problems similar to gatsbyjs.org where frequent painting prevented the site from being interacted with.  This is fixed now, and the site is able to replay for me when testing locally.  I couldn't figure out how to get it to be anything other than a pulsating white circle though (whether recording or not).
