### ISSUE TITLE
[recording] linkedin.com/feed 

### ISSUE THREAD

**Issue by jasonLaster** [WebReplay/webreplay-devtools#178]
I just tried recording linkedin.com/feed and found that it ground to a hault and never completed loading

STR:

1. go to linkedin.com
2. login
3. record

<img width="952" alt="Screen Shot 2020-06-30 at 8 18 06 PM" src="https://user-images.githubusercontent.com/254562/86199457-03bf6580-bb0f-11ea-9ab7-c4d462517124.png">

**Comment by bhackett1024** [comment]
I think this is the same problem as gatsbyjs.org, lots of painting preventing the site from running properly.  That is fixed now, and the site loads for me now, scrolls well, and is able to be completely replayed.
