### ISSUE TITLE
[replaying] gmail

### ISSUE THREAD

**Issue by jasonLaster** [WebReplay/webreplay-devtools#179]
The gmail recording does not seem to finish loading

https://webreplay.io/view?id=cd6c2126-642a-49dd-ad5c-ebdba1562abb

**Comment by bhackett1024** [comment]
I think the problem in the original recording is fixed now, but it's hard to be sure.  This gmail recording I just made loaded fine:

https://webreplay.io/view?id=ab334b31-7727-4a96-af79-72cf1091e0db
