### ISSUE TITLE
[replaying] nytimes.com

### ISSUE THREAD

**Issue by jasonLaster** [WebReplay/webreplay-devtools#180]
Recording steps
1. go to nytimes.com
2. scroll up and down while recording

The recording does not seem to load

[https://webreplay.io/view?id=cf243666-5313-4f28-aa5d-2de2b11c9cd8](https://webreplay.io/view?id=cf243666-5313-4f28-aa5d-2de2b11c9cd8)

**Comment by bhackett1024** [comment]
I'm not sure what the problem here was, but I'm able to replay nytimes.com now:

https://webreplay.io/view?id=2267c2c6-a288-4b86-b041-c317f56d8e10
https://webreplay.io/view?id=dfbf8585-e449-4dd0-af65-d28d47b8e819
