### ISSUE TITLE
Viewer-level zoom

### ISSUE THREAD

**Issue by jasonLaster** [WebReplay/webreplay-devtools#181]
The timeline supports zooming in on a section, which is great for viewing the markers in that section.

Zooming should be app-wide:

1. ensure that the console only show messages in that window
2. ensure we are paused in the window, if we are not, we should seek to the end of the window
3. ensure that resume does not leave the window. i.e. pause at the end

This would be a big win for 2 reasons:

1. performance. Replay performance will be a function of the window size
2. ergonomics. This will make it easier to narrow the debugging search window which is great when debugging big applications

Notes:

- we can implement this without any changes to the UI

**Comment by bhackett1024** [comment]
I think we should table the performance improvements for now.  While this will definitely be nice, it will mainly help for longer recordings which we don't deal with well right now for other reasons.  The ergonomic improvements will be really nice to do now, though.

**Comment by jasonLaster** [comment]
Agreed. I think this is more of a ux win because big recordings can become
a pain with the console etc..

**Comment by bhackett1024** [comment]
Cool, this is fixed now.  Debugger resumes won't leave the zoomed region, and the console only shows messages from the zoomed region.

**Comment by jasonLaster** [comment]
Works great
