### ISSUE TITLE
[recording] reddit.com

### ISSUE THREAD

**Issue by jasonLaster** [WebReplay/webreplay-devtools#189]
Web Replay does not finish recording reddit.com's initial page load

1. go to https://www.reddit.com/
2. click record
3. try to scroll

**Comment by bhackett1024** [comment]
I've seen a couple problems on reddit.  This includes the more general problem that was affecting jam.dev, and some separate backend issues.  These are both fixed now, here is a recording of the reddit home page (there could be other issues though, the site has a lot of media etc.).

https://webreplay.io/view?id=3d52ff35-663f-44fc-aa47-3a895f72c658
