### ISSUE TITLE
[replayer] webreplay.io

### ISSUE THREAD

**Issue by jasonLaster** [WebReplay/webreplay-devtools#190]
I'm struggling with the basic record/replay loop for webreplay.io

1. go to https://webreplay.io/view?id=763ad627-733d-484a-8277-8bae2ae79e0c
2. start recording and jump around
3. attempt to view the new recording

**Comment by bhackett1024** [comment]
I think this was running into the same issue as jam.dev.  We replay recordings of the viewer regularly as part of e2e tests, which has been working pretty reliably when using a fresh profile (the jam.dev bug fixed a problem when recording using an existing profile).
