### ISSUE TITLE
Step back falls into awaits

### ISSUE THREAD

**Issue by jasonLaster** [WebReplay/webreplay-devtools#192]
STR:

1. go to  [recording](https://webreplay.io/view?id=cc5a2b90-b74d-42ce-b7ff-ff6b4e246f19)
2. rewind to 33
3. press step back

ER: go to 32
AR: go to 24

https://www.loom.com/share/68f44f00516e48d1a48c1ef411a93e5e

meta: #123

**Comment by bhackett1024** [comment]
This is the intended behavior.  When stepping we can also stop at installed breakpoints and debugger statements, if they are hit first when traveling forward/backward to the step target.  This could be revisited but it's consistent with what debuggers normally do when stepping (including the non-replay firefox debugger).

**Comment by jasonLaster** [comment]
Hmm, I wonder what i'm missing... I was thinking step over and back would not enter the async function...

**Comment by bhackett1024** [comment]
Well, because there is an await, the async function has to completely execute between the await statement and the following one.
