### ISSUE TITLE
[replaying] Can't expand `front._rule`

### ISSUE THREAD

**Issue by jasonLaster** [WebReplay/webreplay-devtools#198]
STR:
1. go to https://webreplay.io/view?id=6effc94d-5f83-401a-9013-ab54e3d6be85
2. put a breakpoint in protocol/thread.js:235 where  RuleFront is instantiated
3. expand `getDomFront/front/_rule`

ER: see object
AR: infinite loading, probably failed

<img width="1748" alt="Screen Shot 2020-07-04 at 8 41 05 AM" src="https://user-images.githubusercontent.com/254562/86516060-76139c80-bdd2-11ea-908f-ab97725fe9c9.png">

**Comment by bhackett1024** [comment]
This WFM now, I think this was a backend problem that I fixed after seeing in the logs.
