### ISSUE TITLE
Async call stacks are missing frames

### ISSUE THREAD

**Issue by jasonLaster** [WebReplay/webreplay-devtools#201]
I noticed while working on a small async call stack demo that some ancestor frames could be dropped

Here's a video where around minute 4 i notice that `stuff` is missing
https://www.loom.com/share/23007aa1dbbc48a7acf36b018a98aea3

Here is the recording and the example as well

https://webreplay.io/view?id=dd601d24-9fbe-412c-bacb-3e3eec0d783c
https://dbg-async-tasks.glitch.me/

meta: #123

**Comment by bhackett1024** [comment]
This is fixed now.  This was a problem in the backend --- steps in generator frames weren't always sorted, which prevented us from figuring out the original caller (among other problems).
