### ISSUE TITLE
[Debugger] annotate generated variables

### ISSUE THREAD

**Issue by jasonLaster** [WebReplay/webreplay-devtools#203]
It would be nice if we could annotate generated variables that do not appear in the original scopes. This way the UI could treat it it a bit differently:

either

1. hide them by default
2. style them differently with a tooltip

<img width="2254" alt="generated vars" src="https://user-images.githubusercontent.com/254562/86535176-3e205e00-be93-11ea-9664-1aa8e120460b.png">

#### STR:
1. go to https://webreplay.io/view?id=79f58428-6472-4e9d-a738-1f53902bdfef
2. pause in App.js:192

meta #62

**Comment by bhackett1024** [comment]
This makes sense.  I think we should hide them, with no toggle, and have a way to switch back to the generated source and variables.  I find myself missing this when looking at things like this firebugs page --- compiling the source can make some pretty substantial changes to how the code is structured, and it's nice to see what code is actually running on the page.

**Comment by bhackett1024** [comment]
When there are variables with original names in scope, we now hide variables without an original name, except for "arguments".  I'll work on switching to the generated source in a separate issue tomorrow.

https://github.com/WebReplay/webreplay-devtools/commit/9198de392c1f8875046a2b69a0db776a7e6ba5ac
