### ISSUE TITLE
[replaying] jam.dev

### ISSUE THREAD

**Issue by jasonLaster** [WebReplay/webreplay-devtools#206]
The `jam.dev` site could be a great stress case for us

1. go to jam.dev
2. type `jam` to unlock the Jam mode
3. enter email, it can be anything really
4. wait for comments to appear
5. double click on the text in the header "Rock" or whatever
6. add a comment and save

here's a recording where i just did those steps: [link](https://webreplay.io/view?id=cb228550-d852-48bf-951f-cd67940e85e7)

The recording worked, but could have certainly been smoother. The bigger issue is that replaying seems to crash. Note that steps 1-3 and saving seems to work.

**Comment by bhackett1024** [comment]
With some recent recorder fixes this site works for me now.

**Comment by jasonLaster** [comment]
Amazing 🎊
