### ISSUE TITLE
[Evaluation] this.props.setKeyword is `invalid object`

### ISSUE THREAD

**Issue by jasonLaster** [WebReplay/webreplay-devtools#208]
STR:

1. go to https://webreplay.io/view?id=6dbb261f-a978-4b9d-b235-f0f4013ae35d
2. set a breakpoint in `App.js:192` and seek to one of the pause positions
3. in the console, evaluate `this.props`  and expand the object

<img width="730" alt="Screen Shot 2020-07-07 at 8 02 24 PM" src="https://user-images.githubusercontent.com/254562/86870327-10066e00-c08d-11ea-82fd-797ace8c3ef5.png">

**Comment by bhackett1024** [comment]
This WFM now.  I don't know what change fixed it, but this "Invalid object" shows up when there was a problem generating the rep for an object, and there have been a few fixes to the reps code lately.
