### ISSUE TITLE
[Evaluation] `map` returns a generic object

### ISSUE THREAD

**Issue by jasonLaster** [WebReplay/webreplay-devtools#209]
STR:

1. go to https://webreplay.io/view?id=6dbb261f-a978-4b9d-b235-f0f4013ae35d
2. set a breakpoint in `App.js:192` and seek to one of the pause positions
3. in the console, evaluate `this.props.bugs.bugs.map(b => b)`  notice the response is `Object`

<img width="404" alt="Screen Shot 2020-07-07 at 8 02 49 PM" src="https://user-images.githubusercontent.com/254562/86870416-32988700-c08d-11ea-9b7e-8b5892cd5331.png">

**Comment by bhackett1024** [comment]
This should work now, though you'll need to update to the latest browser (the fix was made there) and make a new recording.
