### ISSUE TITLE
[inspector] sourcemap locations

### ISSUE THREAD

**Issue by jasonLaster** [WebReplay/webreplay-devtools#212]
Firefox maps the CSS locations, which lets users see where the style came from e.g. App.css

<img width="1438" alt="Screen Shot 2020-07-08 at 6 41 43 AM" src="https://user-images.githubusercontent.com/254562/86925915-4ae8c000-c0e6-11ea-954a-98627ac9fd64.png">

**Comment by jasonLaster** [comment]
STR:

1. go to https://webreplay.io/view?id=e493e224-b729-4edf-887d-ca96c849caa1
2. open inspector and select `div.App` 

NOTE: the `.app` rule points to `main.<xxx>.chunk.css`

**Comment by bhackett1024** [comment]
This should work now, though you'll need to make a new recording with the latest version of the browser.
