### ISSUE TITLE
[inspector] detect applied properties

### ISSUE THREAD

**Issue by jasonLaster** [WebReplay/webreplay-devtools#213]
It looks like web replay doesn't know if a property is active or applied and therefore greys it out.

<img width="1438" alt="Screen Shot 2020-07-08 at 6 41 43 AM" src="https://user-images.githubusercontent.com/254562/86925990-62c04400-c0e6-11ea-87b5-57965bacf8eb.png">

**Comment by bhackett1024** [comment]
I filed #278 with some more information about what's going on here, but we don't currently support the logic in the Firefox devtools for figuring out whether CSS properties are actually used.  We were supposed to treat them as used by default, but there is a bug that causes them to be unused by default.  Fixing this will color the properties correctly, though #278 will need to be fixed to have parity here with the Firefox devtools.
