### ISSUE TITLE
[recording] discord.com

### ISSUE THREAD

**Issue by jasonLaster** [WebReplay/webreplay-devtools#231]
I think discord crashes when loading

STR:
1. log into discord
2. join gatsby https://discord.com/invite/gatsby
3. start recording
4. refresh... should see a gatsby channel

https://webreplay.io/view?id=a33e50f3-65ae-4790-9783-b06d8439ed6a

**Comment by bhackett1024** [comment]
A few days ago I fixed the issue that was causing this crash (a missing direction) after seeing it in the logs.  I'm able to make a discord recording now:

https://webreplay.io/view?id=2b2a0133-162b-4c4d-9222-6241b87881bf
