### ISSUE TITLE
[replaying] notion.so session died unexpectedly

### ISSUE THREAD

**Issue by jasonLaster** [WebReplay/webreplay-devtools#241]
The notion.so session died unexpectedly

https://webreplay.io/view?id=54d6966f-c85a-4240-b0ff-87edd8b1fcd0

**Comment by bhackett1024** [comment]
This was the same problem as #237 and seems to be fixed now, here is a new notion.so recording.

https://webreplay.io/view?id=2d1a04f8-b8a6-4fe2-a19c-32e2d5070d68
