### ISSUE TITLE
[NodePicker] Incorrect node shown

### ISSUE THREAD

**Issue by jasonLaster** [WebReplay/webreplay-devtools#244]
I think there are some issues finding the correct node to show in the markup view.

I see this a lot in firebugs and other complex apps. I'll get a recording soon

**Comment by jasonLaster** [comment]
Just looked into this and didn't see an obvious bug in the first 5 minutes.

I'll look again tomorrow

**Comment by jasonLaster** [comment]
I looked into this and i think we find the right element, but perhaps fail to load it...

We also have some other breadcrumb / scrolling issues... which i'll file separately.


Notice the "Not allowed" issues, which are coming from `importNode` in markup.js
https://webreplay.io/view?id=0d103e3d-3f46-4a6a-8994-a2f3b9daeab5

**Comment by bhackett1024** [comment]
The "Not allowed" failures are due to the full story instrumentation trying to convert the nodes which get logged into JSON.  I'll remove the console.log call which full story is instrumenting.
