### ISSUE TITLE
[replaying] facebook "session died unexpectedly"

### ISSUE THREAD

**Issue by jasonLaster** [WebReplay/webreplay-devtools#255]
https://webreplay.io/view?id=347db9af-bc81-464a-aacd-3a6eeaf37da5

happened twice in a row

**Comment by bhackett1024** [comment]
There's a backend failure on this recording, which I saw back when it occurred and have added logging in the latest builds.  Without STR there isn't much more to be done here though, the next time this failure happens we'll have more info.
