### ISSUE TITLE
[replaying] Can't add breakpoint in kustomer.com

### ISSUE THREAD

**Issue by jasonLaster** [WebReplay/webreplay-devtools#276]
STR:

1. go to https://webreplay.io/view?id=4b3afc3e-b31f-4dab-8130-89c9f6800f75
2. open api.min.js
3. try and add a breakpoint on 3078 inside of `onload`

**Comment by jasonLaster** [comment]
Here is a recording that captures the assertion failures
https://webreplay.io/view?id=a8451083-19c3-4209-837b-6639aad1dc21

And the problem looks like it is in `chooseScriptId`


<img width="534" alt="Screen Shot 2020-07-27 at 10 54 55 AM" src="https://user-images.githubusercontent.com/254562/88574773-ac21f600-cff7-11ea-9aae-580473bfab23.png">
<img width="587" alt="Screen Shot 2020-07-27 at 10 54 42 AM" src="https://user-images.githubusercontent.com/254562/88574777-adebb980-cff7-11ea-990b-c827a9de3e07.png">

**Comment by bhackett1024** [comment]
hmm, the problem here is that we assume there is only one generated script or HTML file per URL, but as shown in this recording there could be many.  setBreakpointByURL and removeBreakpointByURL need to be updated to handle this case

**Comment by bhackett1024** [comment]
This is fixed now, though the handling of this file is still not great --- there can be multiple source tabs open for the same URL and multiple breakpoints can be visible.  Other parts of the client are not folding together these different sources with the same URL.
