### ISSUE TITLE
Event Listener logpoints

### ISSUE THREAD

**Issue by jasonLaster** [WebReplay/webreplay-devtools#66]
My assumption is that adding keyboard, mouse logpoints should be present in 

http://localhost:8080/index.html?id=25aa6e4b-bc4e-48fd-9f8d-99b8ee99c77d

at the moment i don't see any

**Comment by jasonLaster** [comment]
http://localhost:8080/index.html?id=e3cbdf2e-e093-4705-9330-21f70774461f

^ adding mouse, and keyboard events should show up

**Comment by bhackett1024** [comment]
Mouse and keyboard events now generate logpoints in the above recording.
