### ISSUE TITLE
Inspector highlighter is not aligned

### ISSUE THREAD

**Issue by jasonLaster** [WebReplay/webreplay-devtools#68]
It looks like the work on positioning the viewport threw off the highlighter.

<img width="873" alt="Screen Shot 2020-06-03 at 6 17 41 PM" src="https://user-images.githubusercontent.com/254562/83704305-a0511f00-a5c6-11ea-8fda-c20a998cfb7e.png">

<img width="826" alt="Screen Shot 2020-06-03 at 6 17 49 PM" src="https://user-images.githubusercontent.com/254562/83704299-9cbd9800-a5c6-11ea-92f1-7dbfa2299298.png">

**Comment by jasonLaster** [comment]
In terms of timing, what do you think of going to alpha with the inspector opt-in?

This way we set expectations that the inspector is experimental and focus attention on the debugger + console?

**Comment by bhackett1024** [comment]
When we go to beta the inspector needs to work well --- it's an important devtool and being able to use it with web replay will make it possible to do tasks that are very difficult with normal devtools, like investigate page glitches and inspect DOM state during transitory events like :hover.

The feature set will be pared down to the most important features for this sort of work, though.  Features that I want to make sure will work:

element highlighter
markup pane
applied rules
computed styles
box model information

All of these are somewhat/mostly functional already, and it shouldn't take a lot of time to fix the remaining issues.
